# Generated by Django 4.2.7 on 2025-09-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_add_rank_and_bar_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'User'), ('bartender', 'Bartender'), ('system', 'System')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dream_type',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('adventure', 'Adventure'), ('love', 'Love'), ('mystery', 'Mystery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('newcomer', 'Newcomer 🌱'), ('regular', 'Regular 🍺'), ('connoisseur', 'Connoisseur 🥃'), ('master', 'Master 🍷'), ('legend', 'Legend 👑')], default='newcomer', max_length=20),
        ),
    ]
